image: registry.cn-shenzhen.aliyuncs.com/cangcanglang/vivadosdk2017p2

bootbin:
  - build
  - test
  - deploy

bootbin:
  stage: build
  only: 
    refs:
      - master
  script:
    - git submodule init 
    - git submodule update --init --recursive 
    - make
  tags:
    - blr_runner
  artifacts:
    paths:
      - BOOT.bin
    name: "${CI_JOB_NAME}_${CI_COMMIT_SHA:0:8}"
